language: node_js

node_js: 10

os:
  - windows
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ls /c/Python27/ /c/Program*; fi
  - /c/Python27/python.exe -V || true

script: node -p 'require.resolve("weak");'
