language: node_js

node_js: 10

os:
  - windows
  - linux
  - osx

before_install:
  - if [[ $TRAVIS_OS_NAME == windows ]]; then
    set DEBUG_HELPER=1;
    ./find_python.cmd;
    echo $VCBUILD_PYTHON_LOCATION;
    choco install python2;
    ./find_python.cmd;
    echo $VCBUILD_PYTHON_LOCATION;
    fi
  - echo $PATH;
  - which python2;
  - python2 --version;

script: node -p 'require.resolve("weak");'
