language: node_js

node_js: 10

os:
  - windows
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cinst -y python2; fi

script: winpty node -p 'require.resolve("weak");'
