language: node_js

node_js: 10

os:
  - windows
  - linux
  - osx

before_install:
  - if [[ $TRAVIS_OS_NAME == windows ]]; then
      choco install python;
    fi
  - echo $PATH;
  - which python;
  - python --version;

script: node -p 'require.resolve("weak");'
