language: node_js

node_js: 10

os:
  - windows
  - linux
  - osx

before_install:
  - if [[ $TRAVIS_OS_NAME == windows ]]; then
    choco install python2;
    export PATH="/c/Python27:/c/Python27/Scripts:$PATH";
    fi
  - echo $PATH;
  - which python2;
  - python2 --version;

script: node -p 'require.resolve("weak");'
