language: node_js

node_js: 10

os:
  - windows
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then find /c/ -iname \*python\*; fi

script: node -p 'require.resolve("weak");'
